Pca
GispoCoding/eis_toolkit pull request #101
Opened 2023-03-08 10:08 UTC by dipak5053

we have implemented all the modification according your email!

2023-03-16 13:11 UTC, nmaarnio requested changes
Thanks for making the modifications so fast. The code is already looking pretty good, but there were some style issues that I commented. Also, I think you accidentally pushed the MLP files to this pull request. Please remove them in the next commit you make to this open pull request, and store your MLP in a different branch/PR.

Regarding the tests, do you think it would be possible to make some tests where the result dataframe from the PCA is compared to some hard-coded dataframe that you know for sure has the correct/expected values from the PCA? These dataframes can be small so that hard-coding is possible. These kind of "visual tests" that you have are good, but they ultimately belong to a Jupyter notebook. You can find examples of Jupyter notebook testing in the repository and perhaps transfer your current test to this format.

2023-03-16 13:17 UTC, nmaarnio commented
Also, please remember to run the linter @dipak5053 . If you have issues with it, I can also try to help. You can find the guide for it in [the contributing guide](https://github.com/GispoCoding/eis_toolkit/blob/master/CONTRIBUTING.md#code-style). We have started to use a tool **pre-commit** now. It will check that your coding style is correct when you are making commits, and you can run it manually/disable it also - all this is showed in the guide too. This will make it easier for you and other developers to adhere to the style requirements and reduce the PR reviewing time/work. Please note that before you can use pre-commit, you need to pull the latest additions (the configuration file needed for pre-commit to work) from the master branch. While in your current pca branch, you should be able to run
`git pull origin master`
and get the updates, after which you can activate pre-commit.

2023-03-29 08:28 UTC, zelioluca commented on eis_toolkit/exceptions.py
> +    pass
Hi I m luca! I m helping dipak in coding! Can you clarify this little bit?

2023-03-29 08:31 UTC, zelioluca commented on eis_toolkit/exceptions.py
> +    pass
Ah I got it

2023-03-29 09:46 UTC, dipak5053 commented
Hi,
Hope you are doing well
I have fixed the issue.

Warm regards,
Dipak Kumar Nidhi



On Wed, Mar 29, 2023 at 11:32 AM Luca Zelioli ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In eis_toolkit/exceptions.py
> <https://github.com/GispoCoding/eis_toolkit/pull/101#discussion_r1151577751>
> :
>
> > +class InvalidNumberOfPrincipalComponent(Exception):
> +    """Exception error class for invalid dataframes."""
> +    pass
>
> Ah I got it
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GispoCoding/eis_toolkit/pull/101#discussion_r1151577751>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APNY6UEMA3WO6IWAI5MA5F3W6PXQHANCNFSM6AAAAAAVTSHO2E>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-12 07:43 UTC, Mtk112 approved these changes
Everything looks good to me now.

2023-04-12 09:13 UTC, merged