Add distance computations (Closes #103)
GispoCoding/eis_toolkit pull request #126
Opened 2023-04-21 09:19 UTC by nialov

The function uses the base raster profile to create vector points in the center
of each raster cell. It then calculates the minimum distance to the provided
geometries for each point and consequently adds it as the output raster cell
value.

2023-05-08 21:26 UTC, Mtk112 requested changes
The code looks good to me, however few nitpicky notes and general suggestions relating to linter.

2023-05-08 21:26 UTC, Mtk112 commented on eis_toolkit/spatial_analyses/distance_computation.py
> +    smallest_distance = distances_to_point.min()
To fix no-any-return linter error:
```suggestion
    shortest_distance: float = distances_to_point.min()
```

2023-05-10 05:20 UTC, nialov commented
Thanks for the review @Mtk112 ! I am interested in if using `disallow_any_unimported = True` is worth setting in `mypy.ini` if we then have to annotate most functions with the `#type ignore...` comments to disable it? I believe most libraries we use are quite lacking in type annotations (e.g. `numpy`, `geopandas`, `pandas`, etc.) so reinforcing the rule is quite difficult.

2023-05-10 05:44 UTC, nialov commented on eis_toolkit/spatial_analyses/distance_computation.py
> +    """Calculate smalled distance from geometries to point."""
Renamed and added the type comment.

2023-05-10 05:44 UTC, nialov commented on eis_toolkit/spatial_analyses/distance_computation.py
> +    smallest_distance = distances_to_point.min()
Fixed!

2023-05-10 05:50 UTC, nmaarnio commented
> I am interested in if using `disallow_any_unimported = True` is worth setting in `mypy.ini` if we then have to annotate most functions with the `#type ignore...` comments to disable it?

I just thought about this too yesterday when making a refactoring/style change PR, and I agree we could remove it. I will make another commit to my PR and remove it there, if nobody objects.

2023-05-10 11:47 UTC, nialov commented
Removed the `# type: ignore` annotations!

2023-05-10 12:11 UTC, merged