121 - Code style adjustments and refactoring
GispoCoding/eis_toolkit pull request #128
Opened 2023-05-09 14:17 UTC by nmaarnio

Some code style adjustments and refactoring was made following the discussion in [Improving contribution and style guide issue](https://github.com/GispoCoding/eis_toolkit/issues/121) with some additional changes. 

Changes in this PR:
- Remove _prediction_methods_ and _model_training_ folders
- Add beartype to public functions for automatic argument type checking
- Remove type annotations from function parameters in docstrings (MkDocs can fetch the types from function signature)
- Remove return variable names from docstrings
- Add a missing .md file
- Add comments to exceptions
- Remove, add and order some custom exceptions
- Remove non-copy option from some utility functions
- Refactor and improve some functions, including:
  - Logic
  - Variable names
  - Documentation
  - Testing

2023-05-10 12:19 UTC, nmaarnio commented
Regarding pull requests and repository history, do you think we should start squashing commits when merging to the master branch? I have not needed this feature before, but it seems like a good option to keep the repository history cleaner.

2023-05-10 13:10 UTC, nialov commented
Squashing is quite an advanced `git` concept so I do not recommend knowing how to rebase `git` commits during a pull request to be a requirement for contributors. It is easy (-ish) when the commits you want to squash are in serial order and difficult when they are not. I suppose maintainters can edit branches that are committed to the main repository (I have used `nialov/eis_toolkit` out of habit) and can do squashing if needed. I would apply it selectively when you believe there is need.

I would also not by default squash a pull request to a single commit as the commit messages can be useful in future debugging.

2023-05-12 06:59 UTC, nmaarnio commented
@Mtk112 promised to review this PR, but if you would also have time @nialov to take a quick look it would be appreciated since you have been part of the style & utility functions discussions. I attempted to address everything we discussed (and a few other things), except I did not change our checks to raise exceptions yet.

2023-05-12 08:35 UTC, nialov requested changes

2023-05-12 08:35 UTC, nialov commented on CONTRIBUTING.md
> +Some changes have been made to the style guide:
I think all the conventions applied in this pull request could be mentioned, i.e.

```suggestion
Some changes have been made to the style guide:
- Use `numbers.Number` as the type when both floats and integers are accepted by functions:
```python
from numbers import Number

def func(int_or_float: Number):
    ...
```
```

2023-05-12 08:35 UTC, nialov commented on CONTRIBUTING.md
> +```
```suggestion
- Use beartype's decorator for automatic function argument type checking and import types from `beartype.typing` if a warning is raised by beartype on imports from `typing`:
```python
from beartype import beartype
from beartype.typing import Sequence

@beartype
def my_function(parameter_1: float, parameter_2: bool, parameter_seq: Sequence):
```
```

2023-05-12 08:35 UTC, nialov commented on tests/checks/check_raster_grids_test.py
> +test_dir = Path(__file__).parent.parent
My (personal) convention is to uppercase any module symbols to differentiate them inside functions from local symbols. E.g. `test_dir` -> `TEST_DIR`. Maybe worth considering?

2023-05-12 08:37 UTC, nialov commented
Looks great overall and the naming conventions make things much clearer. I "requested changes" but only the mentioning of `numbers.Number` and `beartype.typing` are actually important. Rest are minor subjective stuff

2023-05-14 20:11 UTC, Mtk112 requested changes
Looks good, only managed to find one additional typo to fix.

2023-05-15 06:45 UTC, nmaarnio commented
Thanks for the reviews, I fixed all that you pointed out. I didn't rename any module symbols yet, but let's keep that in mind.

2023-05-15 07:58 UTC, Mtk112 approved these changes
Looks good!

2023-05-15 09:39 UTC, merged