I added MLP probability
GispoCoding/eis_toolkit pull request #206
Opened 2023-10-13 13:21 UTC by dipak5053

2023-10-25 08:32 UTC, zelioluca commented
sorry for this .idea/misc.xml

2023-10-25 09:29 UTC, zelioluca commented
I made also some test

2023-10-25 09:29 UTC, zelioluca commented
But I think I got old PR there was not some file I put there yesterday

2023-10-26 09:16 UTC, nmaarnio requested changes
Hey Luca, there are still some style stuff that needs to taken care of. Also I was wondering about keeping training and predicting separate, but maybe I misunderstood some logic? And MLP was now done in sklearn and not keras apparently? Thanks for delivering this one fast!

2023-10-26 09:16 UTC, nmaarnio commented on eis_toolkit/deep_learning/mlp_function.py
> +    random_state=0,
type missing here (int?)

2023-10-26 09:16 UTC, nmaarnio commented on eis_toolkit/deep_learning/mlp_function.py
> +        random_state: random state for repeatability of results.
Remember to start docstring sentences with uppercase. There is also one typo

2023-10-26 09:16 UTC, nmaarnio commented on eis_toolkit/deep_learning/mlp_function.py
> +        raise InvalidArgumentTypeException
I'd use here the InvalidParameterValueException and include a comment in the exception

2023-10-26 09:16 UTC, nmaarnio commented on eis_toolkit/deep_learning/mlp_function.py
> +    return prediction
I am thinking should we do the predicting in another function and simply train a model here? We could return a dictionary with the best model, the best score and a list of fold performances or something like that.

2023-10-26 09:16 UTC, nmaarnio commented on eis_toolkit/exceptions.py
> +    """Exception throws when number of split is incompatible."""
I would not add these exceptions but use the InvalidParameterValueException with a comment.

2023-10-26 09:16 UTC, nmaarnio commented on eis_toolkit/model_performance_estimation/model_performance_estimation.py
> +        number_of_split: number used to split the dataset.
Could detail here what is required for the `number_of_split` so that exceptions are not raised.

2023-10-26 09:16 UTC, nmaarnio commented on eis_toolkit/model_performance_estimation/model_performance_estimation.py
> +        raise InvalidNumberOfSplit
This could be InvalidParameterValueException

2023-10-26 09:16 UTC, nmaarnio commented on eis_toolkit/model_performance_estimation/model_performance_estimation.py
> +        raise InvalidCrossValidationSelected
This too InvalidParameterValueException

2023-10-26 09:16 UTC, nmaarnio commented on eis_toolkit/model_performance_estimation/model_performance_estimation.py
> +
beartype

2023-10-26 09:16 UTC, nmaarnio commented on eis_toolkit/model_performance_estimation/model_performance_estimation.py
> +    cross_validation_type: str = "LOOCV", number_of_split: int = 5
Literal to list all the valid cross_validation_types. Then beartype will validate also the input str

2023-10-26 09:16 UTC, nmaarnio commented on eis_toolkit/model_performance_estimation/model_performance_estimation.py
Move this file too to `prediction` (at least for now). Lets not create new high-level folders at least yet.

2023-10-26 09:16 UTC, nmaarnio commented on eis_toolkit/deep_learning/mlp_function.py
You could rename this file just "mlp" I think. Also, please move it under `prediction` and remove the `deep_learning` folder.

2023-10-26 09:24 UTC, zelioluca commented
Ok so i can de couple training score and prediction in three sepatate
phases.... now i m thinking to do some class here...what do you think?

I can take care all the styling stuff!

On Thu, 26 Oct 2023, 12:17 Niko Aarnio, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey Luca, there are still some style stuff that needs to taken care of.
> Also I was wondering about keeping training and predicting separate, but
> maybe I misunderstood some logic? And MLP was now done in sklearn and not
> keras apparently? Thanks for delivering this one fast!
> ------------------------------
>
> In eis_toolkit/deep_learning/mlp_function.py
> <https://github.com/GispoCoding/eis_toolkit/pull/206#discussion_r1372821975>
> :
>
> > +        random_state: random state for repeatability of results.
> +    Return:
> +        a numpy array with prediction (class if is_class_probability is set to false otherwise it return probability).
> +    Raises:
> +        InvalidDatasetException: When the dataset is None.
> +        InvalidArgumentTypeException when the function try to make probability and the threshold is None.
> +    """
>
> ⬇️ Suggested change
>
> -        random_state: random state for repeatability of results.
> -    Return:
> -        a numpy array with prediction (class if is_class_probability is set to false otherwise it return probability).
> -    Raises:
> -        InvalidDatasetException: When the dataset is None.
> -        InvalidArgumentTypeException when the function try to make probability and the threshold is None.
> -    """
> +        random_state: random state for repeatability of results.
> +
> +    Return:
> +        A Numpy array with prediction (class if is_class_probability is set to false otherwise it return probability).
> +
> +    Raises:
> +        InvalidDatasetException: When the dataset is None.
> +        InvalidArgumentTypeException when the function try to make probability and the threshold is None.
> +    """
>
> ------------------------------
>
> In eis_toolkit/deep_learning/mlp_function.py
> <https://github.com/GispoCoding/eis_toolkit/pull/206#discussion_r1372824301>
> :
>
> > @@ -0,0 +1,95 @@
> +import numpy as np
> +from sklearn.neural_network import MLPClassifier
> +
> +from eis_toolkit.exceptions import InvalidArgumentTypeException, InvalidDatasetException
> +from eis_toolkit.model_performance_estimation.model_performance_estimation import performance_model_estimation
> +
> +
> +def train_evaluate_predict_with_mlp(
> +    dataset: np.ndarray,
> +    labels: np.ndarray,
> +    cross_validation_type: str,
>
> This could be Literal["LOOCV", "KFOLD", "SKFOLD"]
> ------------------------------
>
> In eis_toolkit/deep_learning/mlp_function.py
> <https://github.com/GispoCoding/eis_toolkit/pull/206#discussion_r1372824442>
> :
>
> > @@ -0,0 +1,95 @@
> +import numpy as np
> +from sklearn.neural_network import MLPClassifier
> +
> +from eis_toolkit.exceptions import InvalidArgumentTypeException, InvalidDatasetException
> +from eis_toolkit.model_performance_estimation.model_performance_estimation import performance_model_estimation
> +
> +
>
> remember @beartype <https://github.com/beartype>
> ------------------------------
>
> In eis_toolkit/deep_learning/mlp_function.py
> <https://github.com/GispoCoding/eis_toolkit/pull/206#discussion_r1372826433>
> :
>
> > +import numpy as np
> +from sklearn.neural_network import MLPClassifier
> +
> +from eis_toolkit.exceptions import InvalidArgumentTypeException, InvalidDatasetException
> +from eis_toolkit.model_performance_estimation.model_performance_estimation import performance_model_estimation
> +
> +
> +def train_evaluate_predict_with_mlp(
> +    dataset: np.ndarray,
> +    labels: np.ndarray,
> +    cross_validation_type: str,
> +    number_of_split: int,
> +    is_class_probability: bool = False,
> +    threshold_probability: float = None,
> +    is_predict_full_map: bool = False,
> +    solver: str = "adam",
>
> This could be Literal listing the valid options too
> ------------------------------
>
> In eis_toolkit/deep_learning/mlp_function.py
> <https://github.com/GispoCoding/eis_toolkit/pull/206#discussion_r1372827157>
> :
>
> > +from eis_toolkit.exceptions import InvalidArgumentTypeException, InvalidDatasetException
> +from eis_toolkit.model_performance_estimation.model_performance_estimation import performance_model_estimation
> +
> +
> +def train_evaluate_predict_with_mlp(
> +    dataset: np.ndarray,
> +    labels: np.ndarray,
> +    cross_validation_type: str,
> +    number_of_split: int,
> +    is_class_probability: bool = False,
> +    threshold_probability: float = None,
> +    is_predict_full_map: bool = False,
> +    solver: str = "adam",
> +    alpha: float = 0.001,
> +    hidden_layer_sizes: tuple[int, int] = (16, 2),
> +    random_state=0,
>
> type missing here (int?)
> ------------------------------
>
> In eis_toolkit/deep_learning/mlp_function.py
> <https://github.com/GispoCoding/eis_toolkit/pull/206#discussion_r1372829071>
> :
>
> > +        cross_validation_type: selected cross validation method.
> +        number_of_split: number of split to divide the dataset.
> +        is_class_probability: if True the code return probability, otherwise it return class.
> +        is_predict_full_map: if True the function will predict the full dataset otherwise predict only the te4st fold.
> +        threshold_probability: works only if is_class_probability is True, is thresholds of probability.
> +        solver: this is what in keras is called optimizer.
> +        alpha: floating point represent regularization.
> +        hidden_layer_sizes: It represents the number of neurons in the ith hidden layer.
> +        random_state: random state for repeatability of results.
>
> Remember to start docstring sentences with uppercase. There is also one
> typo
> ------------------------------
>
> In eis_toolkit/deep_learning/mlp_function.py
> <https://github.com/GispoCoding/eis_toolkit/pull/206#discussion_r1372830517>
> :
>
> > +    if is_class_probability is not False and threshold_probability is None:
> +        raise InvalidArgumentTypeException
>
> I'd use here the InvalidParameterValueException and include a comment in
> the exception
> ------------------------------
>
> In eis_toolkit/deep_learning/mlp_function.py
> <https://github.com/GispoCoding/eis_toolkit/pull/206#discussion_r1372837465>
> :
>
> > +    # assign to classifier and data a vars I do not like see to much indexing
> +    classifier = best_handler_list[0]
> +
> +    if not is_predict_full_map:
> +        data = best_handler_list[1]
> +    else:
> +        data = dataset
> +
> +    if not is_class_probability:
> +        # predict class
> +        prediction = classifier.predict(data)
> +    else:
> +        # predict proba
> +        prediction = classifier.predict_proba(data)
> +        # assign proba to threshold
> +        prediction[prediction >= threshold_probability] = 1
> +
> +    return prediction
>
> I am thinking should we do the predicting in another function and simply
> train a model here? We could return a dictionary with the best model, the
> best score and a list of fold performances or something like that.
> ------------------------------
>
> In eis_toolkit/exceptions.py
> <https://github.com/GispoCoding/eis_toolkit/pull/206#discussion_r1372837872>
> :
>
> > +class InvalidCrossValidationSelected(Exception):
> +    """Exception thrown when a not valid cv is selected."""
> +
> +
> +class InvalidNumberOfSplit(Exception):
> +    """Exception throws when number of split is incompatible."""
>
> I would not add these exceptions but use the
> InvalidParameterValueException with a comment.
> ------------------------------
>
> In
> eis_toolkit/model_performance_estimation/model_performance_estimation.py
> <https://github.com/GispoCoding/eis_toolkit/pull/206#discussion_r1372838423>
> :
>
> > @@ -0,0 +1,35 @@
> +import sklearn
> +from sklearn.model_selection import KFold, LeaveOneOut, Strat [...]

2023-10-26 09:32 UTC, nmaarnio commented
I can't comment much about how many phases there should be, but I'd prefer if there are no custom classes. It's easier for the plugin to just call some functions that produce relevant output and also keeps the toolkit consistent since we haven't been creating own classes so far

2023-10-26 09:34 UTC, zelioluca commented
I f we put three fuunction there in mlp it is ok?

2023-10-26 09:38 UTC, nmaarnio commented
Should be fine I guess. If they are public so user is supposed to call them directly, just make sure they represent logical steps. If they are private helper functions then there's no problem and there could be even more if you see fit

2023-10-26 10:08 UTC, zelioluca commented
I try to finish it by this evening

2023-10-26 10:50 UTC, zelioluca commented
I put all the function separately, but I left alsoi the one with all in one  just in case

2023-10-26 10:52 UTC, zelioluca commented
let s check the functions before we do for nothing

2023-10-26 12:09 UTC, nmaarnio commented
Would it make sense to have just two functions, one for training and one for predicting? The training would take care of evaluation too automatically and have more parameters. What do you think if you take a look at what I did in PR #210 ?  Just thinking whats the best way to pack these steps. And did you leave the cross-validation loop out on purpose in the new functions?

2023-10-26 12:36 UTC, zelioluca commented
Let s see let s see if i use function like these... train prediction and
eval.. i like to have cross validation as separate entity.

 For me me is the same if you prefere we can like you say. When you do
cross validation you have to create each time new instance of the model new
training and new pred. That why i put all in one function! How do you
prefere it? We can have double: one as one entity and one like this...

 Let s try to finish this pr before the weekend so i can prepare the
fusion!

Now i feel very well and my girfriend has corona

On Thu, 26 Oct 2023, 15:09 Niko Aarnio, ***@***.***> wrote:

> Would it make sense to have just two functions, one for training and one
> for predicting? The training would take care of evaluation too
> automatically and have more parameters. What do you think if you take a
> look at what I did in PR #210
> <https://github.com/GispoCoding/eis_toolkit/pull/210> ? Just thinking
> whats the best way to pack these steps. And did you leave the
> cross-validation loop out on purpose in the new functions?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GispoCoding/eis_toolkit/pull/206#issuecomment-1780985481>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF3KUFKIU4NHOBFAHV2VCGLYBJHGTAVCNFSM6AAAAAA57E3YFWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOBQHE4DKNBYGE>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-10-26 12:50 UTC, nmaarnio commented
Sorry but I'm out of office tomorrow and gotta stop working soon, so I don't think I have time to review this again this week. Maybe you can do make some style preparations for the other functions in the meanwhile.

But regarding how to separate these functions, I think something in between these 3 functions and the 1 original function could work. Did you look at the PR I linked? I think the big function you put first was pretty good, but I was just thinking maybe leaving the predictions in the end out if that makes sense? To create, train and validate a model as step 1, and then when the user is happy the model they created they call a different function to predict with unseen data

2023-10-26 12:53 UTC, zelioluca commented
Ahhh sound good to me! So i prepare everything in my best way and maybe
monday we merge ❤️❤️❤️❤️❤️❤️ have a nice weekend man!!! It is nice working
with you!

On Thu, 26 Oct 2023, 15:50 Niko Aarnio, ***@***.***> wrote:

> Sorry but I'm out of office tomorrow and gotta stop working soon, so I
> don't think I have time to review this again this week. Maybe you can do
> make some style preparations for the other functions in the meanwhile.
>
> But regarding how to separate these functions, I think something in
> between these 3 functions and the 1 original function could work. Did you
> look at the PR I linked? I think the big function you put first was pretty
> good, but I was just thinking maybe leaving the predictions in the end out
> if that makes sense? To create, train and validate a model as step 1, and
> then when the user is happy the model they created they call a different
> function to predict with unseen data
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GispoCoding/eis_toolkit/pull/206#issuecomment-1781059774>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF3KUFPGKRMCXVETIX4BF6LYBJMBZAVCNFSM6AAAAAA57E3YFWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOBRGA2TSNZXGQ>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-10-30 04:41 UTC, zelioluca commented
Niko I added two more function let's see which ones are better!

2023-10-30 09:33 UTC, nmaarnio commented
Hey Luca! Thanks for the update, I took a quick look now and looks pretty good now. I'm thinking about the function interfaces still a little bit. Is your CNN code somewhat similar than this? I am wondering would it make sense to include the CNN code to this PR and look at all of this at the same time 🤔. Also @msmiyels , if you got time beginning of this week, you could take a look at these functions too if you have some ideas!

2023-10-30 09:39 UTC, zelioluca commented
This can be a very good idea we can reduce a cnn to mlp, we just remove the conv2d layer! It is ok if the cnn is written with tensorflow?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Niko Aarnio ***@***.***>
Sent: Monday, October 30, 2023 11:33:52 AM
To: GispoCoding/eis_toolkit ***@***.***>
Cc: Luca Zelioli ***@***.***>; Assign ***@***.***>
Subject: Re: [GispoCoding/eis_toolkit] I added MLP probability (PR #206)


Hey Luca! Thanks for the update, I took a quick look now and looks pretty good now. I'm thinking about the function interfaces still a little bit. Is your CNN code somewhat similar than this? I am wondering would it make sense to include the CNN code to this PR and look at all of this at the same time 🤔. Also @msmiyels<https://github.com/msmiyels> , if you got time beginning of this week, you could take a look at these functions too if you have some ideas!

—
Reply to this email directly, view it on GitHub<https://github.com/GispoCoding/eis_toolkit/pull/206#issuecomment-1784807856>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AF3KUFKJ7QBINA3E7NBMBZTYB5YABAVCNFSM6AAAAAA57E3YFWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOBUHAYDOOBVGY>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2023-10-30 09:42 UTC, nmaarnio commented
Yea it can use tensorflow (so keras?). Do you think MLP should still use sklearn or keras too? But if this idea is ok to you, go ahead and include some CNN code in this PR too and maybe it will be easier to pack all of them in a clever way!

2023-10-30 09:51 UTC, zelioluca commented
If we use tf and keras, we have to remove the probability map, there is not
in keras. Maybe for now we can keep both? I anyway add some code for cnn
with same PR and let s see what  looks like... we keep the best

On Mon, 30 Oct 2023, 11:42 Niko Aarnio, ***@***.***> wrote:

> Yea it can use tensorflow (so keras?). Do you think MLP should still use
> sklearn or keras too? But if this idea is ok to you, go ahead and include
> some CNN code in this PR too and maybe it will be easier to pack all of
> them in a clever way!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GispoCoding/eis_toolkit/pull/206#issuecomment-1784821817>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF3KUFLWTWVXRFHIFDRNPA3YB5ZAXAVCNFSM6AAAAAA57E3YFWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOBUHAZDCOBRG4>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-10-30 10:22 UTC, zelioluca commented
Ah i forget, i m formatting my work pc, so the code will be ready by this evening / tomorrow morning 😛

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Niko Aarnio ***@***.***>
Sent: Monday, October 30, 2023 11:42:35 AM
To: GispoCoding/eis_toolkit ***@***.***>
Cc: Luca Zelioli ***@***.***>; Assign ***@***.***>
Subject: Re: [GispoCoding/eis_toolkit] I added MLP probability (PR #206)


Yea it can use tensorflow (so keras?). Do you think MLP should still use sklearn or keras too? But if this idea is ok to you, go ahead and include some CNN code in this PR too and maybe it will be easier to pack all of them in a clever way!

—
Reply to this email directly, view it on GitHub<https://github.com/GispoCoding/eis_toolkit/pull/206#issuecomment-1784821817>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AF3KUFLWTWVXRFHIFDRNPA3YB5ZAXAVCNFSM6AAAAAA57E3YFWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOBUHAZDCOBRG4>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2023-10-30 10:23 UTC, nmaarnio commented
Yeah no hurry! Tomorrow or even later is ok

2023-10-31 15:07 UTC, zelioluca commented
I did all the necessary function for the CNN / MLP. I need to implement exception and test and I m ready for the PR!

2023-10-31 15:08 UTC, zelioluca commented
ahh I also need to tun it couple of tiime as well :-)

2023-11-01 08:58 UTC, zelioluca commented
hey niko I got this bear type I do not have idea how to fix it 

beartype.roar.BeartypeDecorHintNonpepException: Function __main__.convolutional_body_of_the_cnn() parameter "input_layer" type hint <function Input at 0x7f9d23009f30> either PEP-noncompliant or currently unsupported by @beartype.

2023-11-01 09:27 UTC, zelioluca commented
without bear type is working now

2023-11-01 12:17 UTC, zelioluca commented
OK man I m ready to check the code with you! I removed some bear type cos were little bit pahaa

2023-11-03 06:55 UTC, nmaarnio commented
Hi Luca, I've been a bit busy but maybe I can get you some comments today, sorry for the wait.

2023-11-03 06:59 UTC, zelioluca commented
Hey man how are you?

No problem! Me too I m implementing correction to my thesis! Very boring
and time consuming task😛!

 No rush we can do this on monday if you do not have time today! We are
also almost finished the pr for the rami's code!

On Fri, 3 Nov 2023, 08:55 Niko Aarnio, ***@***.***> wrote:

> Hi Luca, I've been a bit busy but maybe I can get you some comments today,
> sorry for the wait.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GispoCoding/eis_toolkit/pull/206#issuecomment-1791960784>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF3KUFIGT5UVJPBRFAYYU6DYCSINXAVCNFSM6AAAAAA57E3YFWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOJRHE3DANZYGQ>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-11-08 08:54 UTC, zelioluca commented
What we do here with this big boy???? :-)

2023-11-08 09:41 UTC, zelioluca commented
Hi there!!!! Thank you man i will take a look for sure! Yes yes i always
use CV

On Wed, 8 Nov 2023, 11:39 Niko Aarnio, ***@***.***> wrote:

> Hey I was just about to say me and Mika finished creating the new CNN and
> MLP functions. It doesnt include yet multimodal approach and some other
> stuff I wrote as comments in the beginning of the file. So theres a new
> file, I didn't modify any of your work even if our functions are based on
> it. You can already take a look if you want and comment! Still thinking how
> to best include hyperparameter optimization and CV (although how often is
> CV used for these methods?)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GispoCoding/eis_toolkit/pull/206#issuecomment-1801426903>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF3KUFI2MYRNEJPUS3CI4KLYDNHN7AVCNFSM6AAAAAA57E3YFWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBRGQZDMOJQGM>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-02-01 09:38 UTC, nmaarnio commented
Closing as not relevant anymore

2024-02-01 09:38 UTC, closed without merging