280 add MLP CLI functions
GispoCoding/eis_toolkit pull request #412
Opened 2024-06-19 08:30 UTC by nmaarnio

2024-08-07 09:51 UTC, msorvoja requested changes
Looking very good overall! There seems to be some redundant/repetitive code in `cli.py`

2024-08-07 09:51 UTC, msorvoja commented on eis_toolkit/cli.py
> +    huber = "huber"
These are not used and seem to be duplicates to those below.

2024-08-13 11:32 UTC, nmaarnio commented
Ready for another review

2024-08-19 06:38 UTC, msorvoja approved these changes

2024-08-19 07:33 UTC, merged